# Generated by Django 4.1.4 on 2023-06-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0003_rename_common_all_users_alter_all_users_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="All_Users",
            new_name="UserData",
        ),
        migrations.AlterModelTable(
            name="userdata",
            table="UserData",
        ),
    ]
