# Generated by Django 4.1.4 on 2023-06-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0004_rename_all_users_userdata_alter_userdata_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserData",
            new_name="User",
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
