# Generated by Django 4.1.4 on 2023-06-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0005_rename_userdata_user_alter_user_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Data",
        ),
        migrations.AlterModelTable(
            name="data",
            table="Data",
        ),
    ]
