# Generated by Django 4.1.4 on 2023-06-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_App", "0006_rename_user_data_alter_data_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Data",
            new_name="Common",
        ),
        migrations.AlterModelTable(
            name="common",
            table="common",
        ),
    ]
